In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

## Michael Mendoza Lozano

In [2]:
# carga de dataset
digitos = datasets.load_digits()

X = digitos['data']
t = digitos['target']

print(X)
print(t.shape)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
(1797,)


1- Desarrolle una función que simule el $holdout$ $method$. El porcentaje de $X$ que se va a usar para entrenar debe estar parametrizado. No debe usar niguna dependecia a parte de numpy.

In [3]:
def holdoutMethod(trainSize):
    np.random.shuffle(X)
    np.random.shuffle(t)
    testSize=1-trainSize
    splitEX=int(trainSize*len(X))
    splitPX=int(testSize*len(X))
    splitEt=int(trainSize*len(t))
    splitPt=int(testSize*len(t))
    
    X_train = X[:splitEX]
    t_train = t[:splitEt]
    X_test =  X[:splitPX]
    t_test = t[:splitPt]
    
    return X_train,X_test, t_train, t_test

2- Usando la función desarrollada en el punto 2, divida los datos con el 70% para entrenar y el 30% para prueba. Use la dependencia de RNA para clasificar, entrenar y predecir usando tanto el conjunto de entrenamiento como el de pruebas. Use como solver sgd y como función de activación la función logística.
Usando accuracy_score determine la exactitud para t de entrenamiento y t de pruebas <a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html">Ver</a>.

¿Qué resultados obtuvo, intérprete?

In [81]:
train_size=0.70
X_train, X_test, t_train, t_test=holdoutMethod(train_size)

clfx=MLPClassifier(activation = 'logistic', solver = 'sgd', max_iter = 7500).fit(X_train,t_train)
clft=MLPClassifier(activation = 'logistic', solver = 'sgd', max_iter = 7500).fit(X_test,t_test)
tPpredic=clfx.predict(X_train)
tpredic=clft.predict(X_test)
print(accuracy_score(t_test,tpredic))
print(accuracy_score(t_train,tPpredic))


1.0
0.994431185361973


Se obtuvo una exactitud del 100% para el t de pruebas y un 99% para el t de entrenamiento, lo cual nos deja ver que la función de activación logistica se adapta mejor, aunque se demora en converger por esta razon el numero de iteracciones se amplia

3- Siga los siguientes pasos:
* Use Normalizer para normalizar el conjunto de entrenamiento <a href="https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Normalizer.html">Ver</a>.
* Use train_test_split para armar el conjunto de entrenamiento y el conjunto de pruebas. Use 70% para entrenar y 30% para pruebas <a href="https://scikit-learn.org/stable/modules/cross_validation.html#">Ver</a>.
* Use una red neuronal con los parámetros que desee, para generar un buen modelo <a href="https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html">Ver</a>.
* Prediga los resultados para t de entrenamiento y t de pruebas. Usando accuracy_score determine la exactitud para t de entrenamiento y t de pruebas <a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html">Ver</a>. 
* ¿Qué resultados obtuvo? Interprete.

In [95]:
XN = Normalizer().fit(X)
XN =XN.transform(X)
X_train1, X_test1, t_train1, t_test1= train_test_split(XN,t,train_size=0.7)

clf=MLPClassifier(activation = 'tanh', solver = 'lbfgs', max_iter = 2000).fit(X_train1,t_train1)
clf2=MLPClassifier(activation = 'tanh', solver = 'lbfgs', max_iter = 2000).fit(X_test1,t_test1)
tP1predic1=clf2.predict(X_test1)
tpredic1=clf.predict(X_train1)
print((accuracy_score(t_test1,tP1predic1)))
print((accuracy_score(t_train1,tpredic1)))

1.0
1.0


Se obtuvo una exactitud del 100 % para el t de pruebas y un 100% para el t de entrenamiento, ademas de esto se escogio la función de activación tan hiperbólica y el solver lbfgs que nos ayuda a converger un poco mas rapido y si comparamos con el punto 2 las iteracciones necesarias para que converga son menores.

4- Ahora usando cross_val_score con un cv = 7 (<a href="https://scikit-learn.org/stable/modules/cross_validation.html#computing-cross-validated-metrics">Ver</a>), ajuste un buen modelo ¿Qué resultados obtuvo? Interprete.

In [106]:
scores = cross_val_score(clf,XN,t, cv=7, scoring='f1_macro')
print(scores)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

[0.11597923 0.08328835 0.08580369 0.11591377 0.08321929 0.0917124
 0.12544491]
0.10 accuracy with a standard deviation of 0.02
